name: Launch integral system analysis

on:
  watch:
    types: [started]

jobs:
            
  ask-for-authorization:
    name: Ask for authorization
    runs-on: windows-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  launch-integral-system-analysis:
    name: Build -> Test (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [ask-for-authorization]
    strategy:
      fail-fast: true
      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [21,21,21,21,21,21,21,21,21,21,21,21,21,21,21]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
           LOTTERY_UTIL_GOOGLE_CREDENTIAL: ${{ secrets.LOTTERY_UTIL_GOOGLE_CREDENTIAL }}
           resources.integral-system-analysis.folder: 'integralSystemsAnalysis'
           working-path.integral-system-analysis.folder: '/home/runner/work/data'
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml