name: Launch integral system analysis

on:
  watch:
    types: [started]

jobs:
            
  ask-for-authorization:
    name: Ask for authorization
    runs-on: windows-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
  launch-integral-system-indexing-on-JDK-11:
    name: Indexing on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [ask-for-authorization]
    strategy:
      fail-fast: true
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [11]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS }}
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL }}
          RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
          TASKS_MAX_PARALLEL: 5
          TIMEOUT: 20700
          INDEX: 'index'
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml
  
  launch-integral-system-indexing-on-JDK-17:
    name: Indexing on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [ask-for-authorization]
    strategy:
      fail-fast: true
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [17]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS }}
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL }}
          RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
          TASKS_MAX_PARALLEL: 5
          TIMEOUT: 20700
          INDEX: 'index'
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml
        
  launch-integral-system-indexing-on-JDK-21:
    name: Indexing on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [ask-for-authorization]
    strategy:
      fail-fast: true
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [21]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS }}
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL }}
          RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
          TASKS_MAX_PARALLEL: 5
          TIMEOUT: 20700
          INDEX: 'index'
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml
       
  launch-integral-system-analysis:
    name: Analyze on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [launch-integral-system-indexing-on-JDK-11]
    strategy:
      fail-fast: true
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [17,17,17,17,17,17,17,17,17,17,17,17]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS }}
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL }}
          RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
          TASKS_MAX_PARALLEL: 5
          TIMEOUT: 20700
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml

  launch-integral-system-analysis:
    name: Analyze on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [launch-integral-system-indexing-on-JDK-17]
    strategy:
      fail-fast: true
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [17,17,17,17,17,17,17,17,17,17,17,17]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_CREDENTIALS }}
          INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL: ${{ secrets.INTEGRAL_SYSTEM_ANALYSIS_FIREBASE_URL }}
          RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
          TASKS_MAX_PARALLEL: 5
          TIMEOUT: 20700
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml